import AutoStudy.Sqrt2Irrational
import AutoStudy.EnergyConservation
import AutoStudy.DFT.Basic
import AutoStudy.DFT.ManyBody3D
import AutoStudy.DFT.ExplicitHamiltonian
import AutoStudy.DFT.HohenbergKohn
import AutoStudy.DFT.VariationalPrinciple
import AutoStudy.DFT.HohenbergKohnSecond
import AutoStudy.DFT.KohnSham
import AutoStudy.DFT.SelfAdjoint
import AutoStudy.DFT.HellmannFeynman
import AutoStudy.DFT.ExchangeCorrelation
import AutoStudy.DFT.Scaling
import AutoStudy.DFT.FunctionalDerivative
import AutoStudy.DFT.ExactConstraints
import AutoStudy.DFT.ExactConstraints.SumRules
import AutoStudy.DFT.ExactConstraints.Asymptotic
import AutoStudy.DFT.ExactConstraints.SizeConsistency
import AutoStudy.DFT.LDA
import AutoStudy.DFT.GGA
import AutoStudy.DFT.Functionals.Comparison
import AutoStudy.DFT.Functionals.NewFunctional
import AutoStudy.DFT.ModelPotential
import AutoStudy.DFT.Functionals.LB94
import AutoStudy.DFT.Functionals.LB94Asymptotic
import AutoStudy.DFT.Functionals.NLCExamples
import AutoStudy.DFT.Functionals.PhysicalNLC
import AutoStudy.DFT.Functionals.KernelNLC
