import AutoStudy.Sqrt2Irrational
import AutoStudy.EnergyConservation
import AutoStudy.DFT.Basic
import AutoStudy.DFT.HohenbergKohn
import AutoStudy.DFT.VariationalPrinciple
import AutoStudy.DFT.HohenbergKohnSecond
import AutoStudy.DFT.KohnSham
import AutoStudy.DFT.SelfAdjoint
import AutoStudy.DFT.HellmannFeynman
